kind: Deployment
apiVersion: apps/v1
metadata:
  name: nanoleaf
  labels:
    app: nanoleaf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanoleaf
  template:
    metadata:
      labels:
        app: nanoleaf
    spec:
      containers:
        - name: nanoleaf
          image: registry.mkr.house:443/nanoleaf
          imagePullPolicy: Always
          env:
          - name: MQTT_HOST
            value: "192.168.0.8"
          - name: MQTT_PORT
            value: "1883"
          - name: NANOLEAF_HOST
            value: "192.168.1.18,192.168.1.17,192.168.1.16"
          - name: PYTHONUNBUFFERED
            value: "1"
          volumeMounts:
          - name: nanoleaf-config
            mountPath: /root
      volumes:
      - configMap:
          defaultMode: 420
          name: nanoleaf
        name: nanoleaf-config
