apiVersion: v1
data:
  custom.conf: |
    allow_anonymous true
    listener 1883
    protocol mqtt
    listener 9001
    protocol websockets
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mosquitto
