apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  labels:
    app: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      volumes:
      - name: url-shortener-config
        secret:
          secretName: url-shortener-config
      containers:
        - image: registry.mkr.house:443/url_shortener
          name: url-shortener
          ports:
            - containerPort: 80
          env:
            - name: URL_SHORTENER_SHEET_KEY
              valueFrom:
                secretKeyRef:
                  key: sheet_key 
                  name: url-shortener-config
            - name: DOCKER_PORT
              value: "80"
          imagePullPolicy: Always 
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener
  labels:
    app: url-shortener
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 80
  selector:
    app: url-shortener
  type: LoadBalancer
  loadBalancerIP: "192.168.0.9"
  externalTrafficPolicy: Cluster
