apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 30Gi

