apiVersion: v1
kind: Service
metadata:
  name: synapse-postgres-service
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
  type: LoadBalancer
  loadBalancerIP: "192.168.0.99"
  externalTrafficPolicy: Cluster
  selector:
    app: postgres
